---
title: "Tarea10"
author: "JJ"
date: "10/7/2019"
output: html_document
---
```{r}
library(MASS)
datos <- birthwt
```

```{r}
str(datos)
```

```{r}
head(datos)
```

```{r}
help("birthwt")
```


```{r}
datos$race <- as.factor(datos$race)
levels(datos$race) <- c('white', 'black', 'other')

```

```{r}
datos$low <- as.factor(datos$low)
levels(datos$low) <- c('< 2.5kg', '> 2.5 kg')
```


```{r}
prop.table(table(datos$race, datos$low), margin = 1)
```

```{r}
plot(prop.table(table(datos$race, datos$low), margin = 1), main= 'Mosaico',
xlab = 'Raza de la madre', ylab = 'Peso recien nacido')
```

```{r}
barplot(round(prop.table(table(datos$race, datos$low), margin = 1), 3), beside = TRUE, 
        col = c('black', 'white', 'grey'), ylim = c(0, 0.8), legend.text = TRUE, 
        ylab = 'Frecuencia relativa', xlab = 'Peso recien nacidos', 
        main = 'Pesos recien nacidos según raza de la madre')
```

## Madre fumadora y peso del niño

```{r}
datos$smoke <- as.factor(datos$smoke)
levels(datos$smoke) <- c('Yes', 'No')
```

```{r}
prop.table(table(datos$smoke, datos$low), margin = 1)
```

```{r}
plot(prop.table(table(datos$smoke, datos$low), margin = 1), main= 'Mosaico',
xlab = 'Madre fumadora', ylab = 'Peso recien nacido')
```

```{r}
barplot(round(prop.table(table(datos$smoke, datos$low), margin = 1), 3), beside = TRUE, 
        col = c('black', 'white'), ylim = c(0, 0.8), legend.text = TRUE, 
        ylab = 'Frecuencia relativa', xlab = 'Peso recien nacidos', 
        main = 'Pesos recien nacidos según madre fumadora')
```

```{r}
datos$ht <- as.factor(datos$ht)
levels(datos$ht) <- c('No', 'Yes')
prop.table(table(datos$ht, datos$low), margin = 1)
```

```{r}
plot(prop.table(table(datos$ht, datos$low), margin = 1), main= 'Mosaico',
xlab = 'Madre hipertensa', ylab = 'Peso recien nacido')
```
```{r}
barplot(round(prop.table(table(datos$ht, datos$low), margin = 1), 3), beside = TRUE, 
        col = c('black', 'white'), ylim = c(0, 0.8), legend.text = TRUE, 
        ylab = 'Frecuencia relativa', xlab = 'Peso recien nacidos', 
        main = 'Pesos recien nacidos según madre hipertensa')
```
```{r}
prop.table(table(datos$race, datos$smoke, datos$low), margin = 3)
```


```{r}
plot(prop.table(table(datos$race, datos$smoke, datos$low), margin = 3),main= 'Mosaico' )
```


